feat(services): added register service  (#19)
* feat: creation tables

* feat: init auth

* feat: register with  error

* error: fn is not a function

* feat: added register service

* feat: added queries register

* fix: solution require await db